In [2]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
import time

startTime = time.time()
df = pd.read_csv('E:\Downloads\Xtrain_challenge_owkin.csv')
df = df.drop('Ids', axis=1)
print((time.time()-startTime)/60)
df.head()

12.48846675157547

,SNP_0_a,SNP_0_b,SNP_1_a,SNP_1_b,SNP_2_a,SNP_2_b,SNP_3_a,SNP_3_b,SNP_4_a,SNP_4_b,...,SNP_18119_a,SNP_18119_b,SNP_18120_a,SNP_18120_b,SNP_18121_a,SNP_18121_b,SNP_18122_a,SNP_18122_b,SNP_18123_a,SNP_18123_b
0,1,0,0,0,1,0,1,0,1,0,...,0,0,0,0,1,0,1,0,1,0
1,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,1,0,1,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,1,0,1,0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0

In [16]:
#startTime = time.time()
#result = df.mean()
#print((time.time()-startTime)/60)
#result
Y = pd.read_csv('E:\Downloads\y.csv', sep=';', usecols=[1], nrows=100)
Y.head()
#trees=10 Out-of-bag score estimate: 0.572
#trees=20 Out-of-bag score estimate: 0.588
#trees=50 Out-of-bag score estimate: 0.622
#trees=100 Out-of-bag score estimate: 0.642 Out-of-bag score estimate: 0.653 leaf50
#trees=1000 Out-of-bag score estimate: 0.672
#trees=2000 Out-of-bag score estimate: 0.674

   TARGET
0       0
1       0
2       0
3       0
4       1

In [33]:
startTime = time.time()
Y = pd.read_csv('E:\Downloads\y.csv', sep=';', usecols=[1])
forest = RandomForestClassifier(n_estimators=100, oob_score=True, n_jobs=-1, random_state=42)
forest.fit(df, Y.values.ravel())
print((time.time()-startTime)/60)

6.458391658465067

In [40]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score

predicted = forest.predict(df)
accuracy = accuracy_score(Y, predicted)
print(f'Out-of-bag score estimate: {forest.oob_score_:.3}')
print(f'Mean accuracy score: {accuracy:.3}')
#print(roc_auc_score(Y,forest.oob_decision_function_))

Out-of-bag score estimate: 0.642
Mean accuracy score: 1.0

ValueError: bad input shape (26500, 2)

In [ ]:
for i in range (0,36247,2):
 #   df[df.columns[i]] += df[df.columns[i+1]] + 2
  #  df.rename(columns={df.columns[i], 'SNP_' + str(i)}, inplace = True)
    df.drop(df.columns[i+1], axis=1)
df.head()

In [56]:
df.head()

,SNP_0_a,SNP_0_b,SNP_1_a,SNP_1_b,SNP_2_a,SNP_2_b,SNP_3_a,SNP_3_b,SNP_4_a,SNP_4_b,...,SNP_18119_a,SNP_18119_b,SNP_18120_a,SNP_18120_b,SNP_18121_a,SNP_18121_b,SNP_18122_a,SNP_18122_b,SNP_18123_a,SNP_18123_b
0,5,0,0,0,1,0,1,0,1,0,...,0,0,0,0,1,0,1,0,1,0
1,5,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,5,0,1,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,2,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,5,0,1,0,1,0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0

In [19]:
importances = forest.feature_importances_
std = np.std([tree.feature_importances_ for tree in forest.estimators_],
             axis=0)
indices = np.argsort(importances)[::]

# Print the feature ranking
print("Feature ranking:")

for f in range(50):
    print("%d. feature %d (%f)" % (f + 1, indices[f], importances[indices[f]]*1000))

Feature ranking:
1. feature 15889 (0.000000)
2. feature 18651 (0.000000)
3. feature 30875 (0.000000)
4. feature 6081 (0.000000)
5. feature 5659 (0.000000)
6. feature 12545 (0.000000)
7. feature 13081 (0.000000)
8. feature 24049 (0.000000)
9. feature 13895 (0.000000)
10. feature 7121 (0.000062)
11. feature 34099 (0.000069)
12. feature 16339 (0.000069)
13. feature 27429 (0.000070)
14. feature 29859 (0.000133)
15. feature 8091 (0.000140)
16. feature 24257 (0.000140)
17. feature 33647 (0.000141)
18. feature 24539 (0.000142)
19. feature 1805 (0.000142)
20. feature 34855 (0.000144)
21. feature 16803 (0.000175)
22. feature 1911 (0.000191)
23. feature 11565 (0.000200)
24. feature 35045 (0.000201)
25. feature 9947 (0.000203)
26. feature 1135 (0.000209)
27. feature 22659 (0.000210)
28. feature 30567 (0.000212)
29. feature 1363 (0.000213)
30. feature 30185 (0.000214)
31. feature 5087 (0.000214)
32. feature 8831 (0.000214)
33. feature 18501 (0.000218)
34. feature 31867 (0.000222)
35. feature 16683 (0.000224)
36. feature 9385 (0.000235)
37. feature 20987 (0.000240)
38. feature 28319 (0.000242)
39. feature 20223 (0.000253)
40. feature 35093 (0.000261)
41. feature 15189 (0.000264)
42. feature 5527 (0.000264)
43. feature 4321 (0.000267)
44. feature 31675 (0.000269)
45. feature 13519 (0.000273)
46. feature 26915 (0.000273)
47. feature 13041 (0.000275)
48. feature 17897 (0.000276)
49. feature 33423 (0.000276)
50. feature 22975 (0.000277)

In [29]:
sample_leaf_options = [1,5,10,50,100,200,500]
for leaf_size in sample_leaf_options :
    model = RandomForestClassifier(n_estimators= 200, oob_score = True, n_jobs = -1,random_state =42, max_features = "auto", min_samples_leaf = leaf_size)
    model.fit(df, Y)
    print(f'Out-of-bag score estimate: {forest.oob_score_:.3}')

C:\Users\Paul\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

Out-of-bag score estimate: 0.653

C:\Users\Paul\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

Out-of-bag score estimate: 0.653

C:\Users\Paul\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

Out-of-bag score estimate: 0.653

C:\Users\Paul\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

Out-of-bag score estimate: 0.653

C:\Users\Paul\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

KeyboardInterrupt: